name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: |
          yarn one
      - name: deploy
        uses: foxundermoon/now-deploy-action@master
        id: deploy
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          zeit-team-id: team_IcdA4KZF7VghnRhAtBMuOr66
          now-args: '--no-clipboard -c'
          working-directory: ./packages/website
      - name: deploy website preview success
        uses: foxundermoon/feishu-action@v1
        with:
          url: ${{ secrets.FEISHU_BOT }}
          title: 《${{ github.event.pull_request.title }}》deploy success for preview 
          text: |
            preview: ${{ steps.deploy.outputs.preview-url }}
            PR: ${{ github.event.pull_request._links.html.href }}
            committer: ${{ github.actor }}
            repo: ${{ github.event.repository.html_url }}

      - name: deploy website preview failed
        uses: foxundermoon/feishu-action@v1
        if: failure()
        with:
          url: ${{ secrets.FEISHU_BOT }}
          title: deploy failure for website preview 
          text: |
            run detail: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
            PR: ${{ github.event.pull_request._links.html.href }}
            repo: ${{ github.event.repository.html_url }}
